version: "3.9"

services:
  api:
    image: swaggerapi/petstore3:1.0.9
    ports:
      - "8090:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8080 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 2

  test_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BASE_URL=http://api:8080/api/v3
    depends_on:
      api:
        condition: service_healthy
    command: ["pytest", "--html=report.html", "-s", "--maxfail=1", "--disable-warnings"]
    volumes:
      - .:/app
